### ISSUE TITLE
Explain why xhost is needed and address security concerns

### ISSUE THREAD

**Issue by gotjoshua** [AppFlowy-IO/AppFlowy-Docs#3]
The docker setup includes these two lines:

> Step 3: Provide access of appflowy to X session
> `xhost local:root`

I've set up a fair number of docker apps, and haven't seen it before, so it raises a yellow flag.

[seems harmless enough in this context](https://stackoverflow.com/questions/63884968/why-is-xhost-considered-dangerous) but some more details about why its needed will be great.

**Comment by MikeWallaceDev** [comment]
Hi @gotjoshua thanks for bringing that to our attention. I didn't write the Dockerfile, it was provided by a contributor. Honestly, it doesn't work on my system, so I can't really test it out for alternatives.

What do you suggest that we add to the documentation?
In the future, when referring to the documentation, please use the [Documentation repo](https://github.com/AppFlowy-IO/docs)
You can actually clone the documentation repo and submit a PR with your text. 
Thanks!

**Comment by gotjoshua** [comment]
> In the future, when referring to the documentation, please use the [Documentation repo](https://github.com/AppFlowy-IO/docs)

isn't this issue in the docs repo?
(confused)

i actually don't understand it enough to know what to write, thats why i asked...

**Comment by MikeWallaceDev** [comment]
Oh geez, I'm sorry! Hahaha, my bad :-D

Well, I don't anything about it. The whole Dockerfile was a PR, and I didn't even know what xhost was. I looked into it through your links, and didn't see much to concern me. So that's why I asked you. :-)

Hopefully that Docker container won't be needed soon...

**Comment by annieappflowy** [comment]
Hi @gotjoshua , @PabloCastellano has made improvements based on the feedback. Can you check if your concern is resolved?

**Comment by gotjoshua** [comment]
Looks good to me!

**Comment by annieappflowy** [comment]
Thanks for confirming. Closing the issue now
