### ISSUE TITLE
[Write for AppFlowy] How To's: How to Contribute to Appflowy

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy-Docs#74]
How to make coding contributions to appflowy
2.1 How to connect with the team.
2.2 How to identify and solve your first PR.
2.3 How to propose new features for Appflowy (via GitHub Issues)
2.4 An Example on how to handle your first PR, including documentation standards used, as well as good code practices.

How to best engage with the community
3.1 General guidelines on the community, and how to approach contributions with the help of the community.

Links to Resources to help get started with technical contributions:
5.1 Flutter
5.2 Rust
5.3 Git & GitHub + Working via GitHub Flows

Other Initiatives:
6.1 Appflowy Mentorship Program (Link to How-To's for Appflowy Mentorship Program if blog post has been  made)

Conclusion
7.1 General Summary/Conclusion.

**Comment by JRS296** [comment]
Kindly assign the same at the earliest, thanks! @annieappflowy

**Comment by JRS296** [comment]
Hey @annieappflowy, I've started work on the article, Do we make a pr to the gitbook on appflowy-docs for our draft? If so, which section do we save the draft.md file?

**Comment by annieappflowy** [comment]
Please submit a PR in https://github.com/AppFlowy-IO/AppFlowy-Docs to make changes to https://github.com/AppFlowy-IO/AppFlowy-Docs/blob/main/essential-documentation/contribute-to-appflowy/write-for-appflowy/drafts/draft-how-to-contribute-to-appflowy.md

**Comment by JRS296** [comment]
@annieappflowy I think we can close this issue. Resolved by #77, #86 and #92
