### ISSUE TITLE
[Doc] Proposal for Relicensing AppFlowy Docs from AGPL to CC-BY-SA

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy-Docs#75]
According to our legal consultant, CC-BY or CC-BY-SA is more suitable for documentation. We decide to relicense AppFlowy Docs from AGPL 3.0 to CC-BY-SA. The timeline for re-licensing:

- [x] May 1st: All future contributions to https://github.com/AppFlowy-IO/AppFlowy-Docs will be under CC-BY-SA
- [x] May 2nd: Seek consent from past contributors to this repo who have not signed a CLA with us
- [ ] May 31: Begin removing or rewriting documentation that cannot be relicensed

The purpose of this post is to create transparency into this upcoming change and open up discussions in the community.

**Comment by Narcos101** [comment]
Hey @annieappflowy Can I remove or rewrite the existing documentation that cannot be relicensed?

**Comment by annieappflowy** [comment]
Yes, that would be great! @Narcos101 , are you still available to work on rewriting the PRs I linked above?

**Comment by Narcos101** [comment]
@annieappflowy Will start working on it right away!

**Comment by Narcos101** [comment]
hey @annieappflowy i think the #35, the file for it has been shifted to another directory and significant changes have been made to it i.e [New](https://github.com/AppFlowy-IO/AppFlowy-Docs/blob/main/essential-documentation/contribute-to-appflowy/software-contributions/troubleshooting.md). Do you still want it to be refactored? I have successfully rewritten for the remaining two. This one is the only remaining!

**Comment by annieappflowy** [comment]
We can leave #35 as it is. Thanks for the great work!

**Comment by annieappflowy** [comment]
Done
