### ISSUE TITLE
[Fix] How to Contribute to Appflowy

### ISSUE THREAD

**Issue by JRS296** [AppFlowy-IO/AppFlowy-Docs#85]
Regarding few requested changes that need to be fixed:

- [x] Title Case - use: https://capitalizemytitle.com/
- [x] Line 47, shorten it 
- [x] Line 123, shorten it
- [x] Line 78
- [x] Line 149
- [x] General tone improvement + making text more concise where required
- [x] General Grammar check
- [ ] Improving image resolution on Appflowy Docs?

**Comment by JRS296** [comment]
@annieappflowy I can add these changes in a seperate PR. However if the editor will be taking care of it all, I'll close this issue 👍

**Comment by annieappflowy** [comment]
Please do before I bring in our editor. Thanks
