### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by yumin2002** [AppFlowy-IO/AppFlowy-Docs#87]
The link for How we built AppFlowy with Flutter and Rust is incorret, it links to https://github.com/AppFlowy-IO/AppFlowy. Instead, it should link to https://blog-appflowy.ghost.io/tech-design-flutter-rust/.
<img width="1426" alt="Screen Shot 2023-05-20 at 03 11 12" src="https://github.com/AppFlowy-IO/AppFlowy-Docs/assets/94658575/5b140dde-3d55-425d-aec9-be206e4dddb4">

**Comment by annieappflowy** [comment]
Updated. Thank you
