### ISSUE TITLE
Broken link for "How to Create a Plugin for AppFlowy Editor"

### ISSUE THREAD

**Issue by yumin2002** [AppFlowy-IO/AppFlowy-Docs#89]
As below:
Please follow this link: https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/how-tos/how-to-create-a-plugin-for-appflowy-editor

<img width="1433" alt="Screen Shot 2023-05-21 at 04 53 45" src="https://github.com/AppFlowy-IO/AppFlowy-Docs/assets/94658575/359df57a-5950-4ae8-be70-8d8c8f4999d4">

<img width="1426" alt="Screen Shot 2023-05-21 at 04 56 59" src="https://github.com/AppFlowy-IO/AppFlowy-Docs/assets/94658575/eb8460e2-af91-455e-b927-0cfecea71585">

**Comment by annieappflowy** [comment]
Updated. Thank you
