### ISSUE TITLE
[Write for AppFlowy] How To's: How to add new property to appflowy database

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy-Docs#94]
Will discuss how appflowy database overally works, some insights on how it's possible introuducing new property, group by, filtering and filter options. Plus a more detailed guide to how add new property to appflowy database with updated at and created at property as an example.

1 - AppFlowy Database
general explanation that flowy database is behind Appflowy grid, board, calendar view.
1.1 - Entities
1.1.1 - Cell
1.1.2 - Field
1.1.3 - Row
1.1.4 - Sort
1.1.5 - Filter
1.1.5.1 - Where to start with adding new filter condition
1.1.6 - Group
1.1.6.1 - Where to start with adding new group by
1.2 - Services
1.3 - Events

2 - How to add new property
2.1 - Lets create new property "Created At" and "Updated At"
2.1.1 - Adding the new field type
2.1.2 - Hooking into events

**Comment by zoli** [comment]
Commenting here to assign this issue.

**Comment by annieappflowy** [comment]
Assigned. Thanks, @zoli
